/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_store_MyNDK */

#ifndef _Included_com_example_android_store_MyNDK
#define _Included_com_example_android_store_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_store_MyNDK
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_android_store_MyNDK_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
